### ISSUE TITLE
Typo "paradse" should be "paradise"

### ISSUE THREAD

**Issue by trunksbomb** [MidnightPlugins/Midnight-Scrapyard#3]
https://github.com/MidnightPlugins/Midnight-Scrapyard/blob/d962c27cca7f960136127e40f5f97ebdeb9deafa/data/missions%20expeditionary%20fleet.txt#L42

In the future do you prefer an issue or just tagging you in Discord. If tagging, what is your username?

**Comment by trunksbomb** [comment]
Oh and "scanning the planet for signs [...] Fortunately, there is none" should be "there are none" since we're talking about plural signs.

**Comment by MidnightPlugins** [comment]
Thanks, will update. I check discord more often.
