### ISSUE TITLE
Unable to land on Dock 13

### ISSUE THREAD

**Issue by Drasli-Tana** [MidnightPlugins/Midnight-Scrapyard#4]
Hello,

Upon trying to land on the dock 13 to complete the mission, the target switchs to the station itself, thus preventing landing.
Leaving and re-entering system does select the right landing option but is not recognized when trying to do so.

OS: Debian 12
Launcher: ES2 Launcher
Game version: Both latest stable (0.10.4) and continuous (d123014)

Tested with midnight Plugins only
![image](https://github.com/MidnightPlugins/Midnight-Scrapyard/assets/100795666/57679a1c-db85-4b04-8399-6e23da9b6db6)
 and almost all plugins installed active.
![plugins](https://github.com/MidnightPlugins/Midnight-Scrapyard/assets/100795666/d30a26d8-b445-4feb-a394-2dde580b748f)

Video of the issue: 
https://github.com/MidnightPlugins/Midnight-Scrapyard/assets/100795666/bb5f275b-2eae-4c0d-80b0-3e1bfa67f185

Save file with mission active
- Note: this was used with all plugins, so many missions are unavailable
[Drasli Tana 2.txt](https://github.com/MidnightPlugins/Midnight-Scrapyard/files/14172591/Drasli.Tana.2.txt)

**Comment by MidnightPlugins** [comment]
Have you tried using the Port tab on the map screen to select Docking Bay 13 and land on it?
